name: Install Solana

inputs:
  version:
    description: The Solana version to install
    required: true
    default: "stable"
  cache:
    description: Whether the downloaded Solana release should be cached
    required: true
    default: "true"

env:
  BASE_URL: ""

runs:
  using: "composite"
  steps:
    - name: Cache Solana
      id: cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/share/solana/install/releases/${{ inputs.version }}
          ~/.cache/solana
        key: ${{ runner.os }}-solana-v${{ inputs.version }}

    - name: Set install URL
      id: version_check
      run: |
        desired="${{ inputs.version }}"
        cutoff="1.17.25"
        if [ "$(printf '%s\n' "$cutoff" "$desired" | sort -V | head -n1)" = "$desired" ] && [ "$cutoff" != "$desired" ]; then
          echo "BASE_URL='release.solana.com'" >> $GITHUB_ENV
        else
          echo "BASE_URL='release.anza.xyz'" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install Solana
      if: inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true'
      run: |
        sh -c "$(curl -sSfL https://${{ env.BASE_URL }}/v${{ inputs.version }}/install)"
      shell: bash

    - name: Set Active Solana Version
      run: |
        rm -f "$HOME/.local/share/solana/install/active_release"
        ln -s "$HOME/.local/share/solana/install/releases/${{ inputs.version }}/solana-release" "$HOME/.local/share/solana/install/active_release"
      shell: bash

    - name: Add Solana bin to Path
      run: |
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Solana install
      run: |
        solana --version
      shell: bash
