name: Resolve changed program matrix

inputs:
  programs:
    description: A JSON array of all program names
    required: true
  changes:
    description: A JSON array of changed filters from "dorny/paths-filter"
    required: true
  prefix:
    description: A prefix to prepend to the program name when searching for filters
    required: true
    default: ""
  suffix:
    description: A suffix to append to the program name when searching for filters
    required: true
    default: ""

outputs:
  programs:
    description: A JSON array of programs that have changed
    value: ${{ steps.resolver.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Resolve changed program matrix
      id: resolver
      env:
        PROGRAMS: ${{ inputs.programs }}
      run: |
        CHANGES=$(echo ${{ toJSON(inputs.changes) | sed 's/-/_/g' }})
        KEYS=$(echo $PROGRAMS | jq -c '.[]' | sed 's/"//g')
        CHANGED_KEYS=$(for key in $KEYS; do
          change_key=$(echo $key | sed 's/-/_/g' | sed 's/^/${{ inputs.prefix }}/' | sed 's/$/${{ inputs.suffix }}/')
          index=$(echo $CHANGES | jq -c ". | index(\"$change_key\")")
          if [ $(echo $index) != 'null' ]; then
            echo $key
          fi
        done)
        echo "matrix=$(echo "$CHANGED_KEYS" | jq -R . | jq -sc . | sed 's/""//')" | tee $GITHUB_OUTPUT
