name: Install Node.js with PNPM

inputs:
  version:
    description: The Node.js version to install
    required: true
    default: "18.x"
  dependencies:
    description: whether to install dependencies on the root folder
    required: true
    default: "false"
  cache:
    description: Whether installed dependencies should be cached
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.version }}
        cache: "pnpm"

    - name: Cache Node.js dependencies
      id: cache
      if: inputs.dependencies == 'true' && inputs.cache == 'true'
      uses: actions/cache@v3
      with:
        path: ./node_modules/
        key: ${{ runner.os }}-node-v${{ inputs.version }}-${{ hashFiles('./pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-v${{ inputs.version }}
          ${{ runner.os }}-node

    - name: Install dependencies
      if: inputs.dependencies == 'true' && (inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true')
      run: pnpm install --frozen-lockfile
      shell: bash
