name: Filter matrix

inputs:
  matrix:
    description: A JSON array of names
    required: true
  changes:
    description: A JSON array of changed filters from "dorny/paths-filter"
    required: true
  prefix:
    description: A prefix to prepend to the name when searching for filters
    required: true
    default: ""
  suffix:
    description: A suffix to append to the name when searching for filters
    required: true
    default: ""

outputs:
  matrix:
    description: A JSON array of name that have changed
    value: ${{ steps.filter.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Filter matrix
      id: filter
      env:
        ORIGINAL: ${{ inputs.matrix }}
      run: |
        CHANGES=$(echo ${{ toJSON(inputs.changes) | sed 's/-/_/g' }})
        ORIGINAL_KEYS=$(echo $ORIGINAL | jq -c '.[]' | sed 's/"//g')
        CHANGED_KEYS=$(for key in $ORIGINAL_KEYS; do
          change_key=$(echo $key | sed 's/-/_/g' | sed 's/^/${{ inputs.prefix }}/' | sed 's/$/${{ inputs.suffix }}/')
          index=$(echo $CHANGES | jq -c ". | index(\"$change_key\")")
          if [ $(echo $index) != 'null' ]; then
            echo $key
          fi
        done)
        echo "matrix=$(echo "$CHANGED_KEYS" | jq -R . | jq -sc . | sed 's/""//')" | tee $GITHUB_OUTPUT
