name: Cache all program dependencies

inputs:
  folder:
    description: Path to the folder containing the programs (without trailing slash)
    required: true
    default: "./programs"
  key:
    description: A unique key prefix for the cache
    required: true
    default: "programs"

runs:
  using: "composite"
  steps:
    - name: Cache all program dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ${{ inputs.folder }}/target/
          ${{ inputs.folder }}/**/target/
        key: ${{ runner.os }}-${{ inputs.key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.key }}
